"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { ArrowRight, ChevronDown, Clock3, Globe2, Play } from "lucide-react";

const regions = ["🇰🇪 Kenya", "🇺🇸 United States", "🇬🇧 England", "🇿🇦 South Africa", "🇳🇬 Nigeria", "🇨🇦 Canada", "🇦🇺 Australia", "🇮🇳 India", "🇦🇪 United Arab Emirates", "🇩🇪 Germany", "🇫🇷 France", "🇧🇷 Brazil", "🇯🇵 Japan", "🇸🇬 Singapore"];

export default function HomePage() {
  const [openMenu, setOpenMenu] = useState(false); const [region, setRegion] = useState(regions[0]); const [seconds, setSeconds] = useState(26066);
  useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => value > 0 ? value - 1 : 86399), 1000); return () => window.clearInterval(timer); }, []);
  const clock = [Math.floor(seconds / 3600), Math.floor(seconds % 3600 / 60), seconds % 60].map((value) => String(value).padStart(2, "0")).join(":");
  return <main className="bright-home"><header className="bright-nav"><a href="/" className="bright-brand"><span>K</span>Kora<sup>®</sup></a><nav><a href="#home">Home</a><a href="/how-it-works">About</a><div className="bright-menu" onMouseEnter={() => setOpenMenu(true)} onMouseLeave={() => setOpenMenu(false)}><button aria-expanded={openMenu}>Learning <ChevronDown size={14} /></button>{openMenu && <div className="bright-popover"><a href="/curricula"><b>Curriculum paths</b><span>Kenya, USA and England</span></a><a href="/learn"><b>Learning Studio</b><span>Start an interactive mission</span></a><a href="/how-it-works"><b>How it works</b><span>Meet the learning engine</span></a></div>}</div><a href="/schools">Schools</a><a href="/families">Families</a></nav><div className="bright-actions"><a href="/learn">Log in</a><a href="/learn">Get started <ArrowRight size={14} /></a></div></header>
    <section className="bright-hero" id="home"><div className="bright-copy"><p className="bright-eyebrow">International interactive learning</p><h1><span>LEARN</span> with purpose.<br /><em>BUILD</em> confidence.<br /><b>GO</b> further.</h1><p>Kora makes every curriculum a living route: interactive experiences, evidence of understanding, and a next step shaped around the learner.</p><div className="bright-buttons"><a href="/learn">Explore Kenya CBE <ArrowRight size={17} /></a><button><Play size={14} fill="currentColor" /> See Kora in action</button></div><div className="bright-region"><Globe2 size={17} /><div><small>Where are you learning?</small><select value={region} onChange={(event) => setRegion(event.target.value)} aria-label="Select your region">{regions.map((item) => <option key={item}>{item}</option>)}</select></div></div></div><div className="guide-stage" onContextMenu={(event) => event.preventDefault()}><div className="guide-halo" /><div className="guide-panel"><p>YOUR LEARNING STARTS HERE</p><strong>Kenya CBE<br />Grade 4</strong><span>Mathematics · Fractions</span></div><Image src="/images/kora-learning-guide.png" alt="Kora learning guide holding a tablet" width={1024} height={1536} priority className="guide-image" draggable={false} onDragStart={(event) => event.preventDefault()} /></div></section>
    <section className="bright-metrics"><article><b>🇰🇪</b><div><strong>Kenya CBE</strong><span>Available now</span></div></article><article><b>01</b><div><strong>One shared learning engine</strong><span>Built for every curriculum layer</span></div></article><article><b>↗</b><div><strong>Evidence over completion</strong><span>Learning adapts as understanding grows</span></div></article><article className="timer"><Clock3 size={18} /><div><span>Next adaptive challenge in</span><strong>{clock}</strong></div></article></section></main>;
}
