"use client";

import { useEffect, useState } from "react";
import { ArrowRight, ChevronDown, Clock3, Globe2, Play, Sparkles } from "lucide-react";
const regions = ["🇰🇪 Kenya", "🇺🇸 United States", "🇬🇧 England", "🇿🇦 South Africa", "🇳🇬 Nigeria", "🇨🇦 Canada", "🇦🇺 Australia", "🇮🇳 India", "🇦🇪 United Arab Emirates", "🇩🇪 Germany", "🇫🇷 France", "🇧🇷 Brazil", "🇯🇵 Japan", "🇸🇬 Singapore"];
export default function HomePage() {
  const [openMenu, setOpenMenu] = useState(false); const [region, setRegion] = useState(regions[0]); const [seconds, setSeconds] = useState(26066);
  useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => value > 0 ? value - 1 : 86399), 1000); return () => window.clearInterval(timer); }, []);
  const hours = String(Math.floor(seconds / 3600)).padStart(2, "0"); const minutes = String(Math.floor(seconds % 3600 / 60)).padStart(2, "0"); const secs = String(seconds % 60).padStart(2, "0");
  return <main className="global-home"><header className="global-nav"><a href="/" className="global-logo"><span>K</span>Kora</a><nav><a href="#story">Home</a><div className="nav-menu" onMouseEnter={() => setOpenMenu(true)} onMouseLeave={() => setOpenMenu(false)}><button aria-expanded={openMenu}>Explore <ChevronDown size={14} /></button>{openMenu && <div className="nav-popover"><a href="/curricula"><b>Curriculum paths</b><span>Kenya, USA, England</span></a><a href="/learn"><b>Learning Studio</b><span>Try an interactive mission</span></a><a href="/how-it-works"><b>How Kora adapts</b><span>See the learning engine</span></a></div>}</div><a href="/families">For families</a><a href="/schools">For schools</a></nav><div className="global-actions"><a href="/learn">Log in</a><a className="global-cta" href="/learn">Get started <ArrowRight size={15} /></a></div></header>
    <section className="global-hero" id="story"><div className="hero-orbit orbit-a" /><div className="hero-orbit orbit-b" /><div className="global-copy"><p className="global-kicker"><Sparkles size={14} /> International interactive learning</p><h1>Every learner deserves a route that <em>responds.</em></h1><p>Kora connects curriculum, interactive practice, evidence, and an intelligent next step—so learning becomes personal without losing where it needs to go.</p><div className="global-buttons"><a className="global-primary" href="/learn">Begin your learning route <ArrowRight size={17} /></a><button><Play size={15} fill="currentColor" /> Watch how it works</button></div><div className="region-row"><Globe2 size={17} /><div><span>Where are you learning?</span><select value={region} onChange={(event) => setRegion(event.target.value)} aria-label="Select your region">{regions.map((item) => <option key={item}>{item}</option>)}</select></div><small>Curriculum availability adapts to your region.</small></div></div>
      <div className="hero-console" aria-label="Kora learning route preview"><div className="console-head"><div className="console-logo">K</div><span>Amara&apos;s learning route</span><i /><div className="console-avatar">AN</div></div><div className="console-content"><aside><span className="active">⌂</span><span>▣</span><span>◌</span><span>◒</span></aside><section><p className="console-meta">Kenya CBE · Grade 4</p><h2>Your next meaningful step</h2><div className="console-grid"><article className="course-preview"><div className="preview-art"><b>¾</b><i /><i /><i /></div><p>Mathematics</p><h3>The mango stall</h3><span>Fractions · interactive mission</span><div className="mini-progress"><i /></div></article><article className="route-preview"><p>Learning route</p><div><b>01</b><span>Explore fair shares</span></div><div className="done"><b>02</b><span>Build equal groups</span></div><div><b>03</b><span>Explain your thinking</span></div></article></div></section></div><footer><span><Clock3 size={14} /> New adaptive challenge in</span><b>{hours}:{minutes}:{secs}</b><a href="/learn">Open studio <ArrowRight size={14} /></a></footer></div>
    </section><section className="global-proof"><span>Not a content library.</span><strong>Curriculum-aware learning that changes with the learner.</strong><div><b>Kenya CBE</b><i /> <b>USA standards</b><i /> <b>England curriculum</b></div></section></main>;
}
